# Generated by Django 4.2 on 2023-07-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Annoucement', 'Announcement')], default='Blog', max_length=20),
        ),
    ]
