# Generated by Django 4.2 on 2023-07-18 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_blog_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
